<%@ Page Language="C#"  AutoEventWireup="true" CodeBehind="Principal.aspx.cs" Inherits="Parcial.Principal" %>


<!DOCTYPE html>

<html>
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"/>

<webopt:bundlereference runat="server" path="~/Content/css" />


</head>
<body>
        <div id="Header" class="alert alert-secondary" role="alert">
            <asp:Label ID="lbl_label1" runat="server" ></asp:Label>            
        </div>

        <form runat="server">

        <div id="Menu" class="container" >    
            <nav runat="server" class="row justify-content-md-center"   >
          
            
                    <asp:Button ID="btn_inicio" class="btn btn-dark" runat="server" OnClick="btn_inicio_Click" Text="Inicio" />
              
              
                    <asp:Button ID="btn_nuevoUsuario" class="btn btn-dark" runat="server" OnClick="btn_nuevoUsuario_Click" Text="Nuevo Usuario" />
              
              
                    <asp:Button ID="btn_ordenPuntaje"  class="btn btn-dark" runat="server" OnClick="btn_ordenPuntaje_Click" Text="Ordenar por puntaje" Width="197px" />
              
              
                    <asp:Button ID="btn_ordenNombre" class="btn btn-dark" runat="server" OnClick="btn_ordenNombre_Click" Text="Ordenar por nombre" />

            </nav>
            <asp:label id="Message"
            class ="row justify-content-md-center"
            forecolor="Red"          
            runat="server"/>
            
        
        </div>
      <br/>
          <asp:GridView AutoGenerateEditButton="True"
              OnRowCancelingEdit="cancelaredicion" 
              OnRowEditing="editar"
              OnRowUpdating="actualizar"
              OnRowDeleted="borrado"
              OnRowDeleting="borrando"
              runat="server"
              ID="GridView1" 
              CssClass="table table-striped"
              HorizontalAlign="Center" 
              PageSize="5" Width="800px" 
              OnSelectedIndexChanged="GridView1_SelectedIndexChanged" 
              CellPadding="4"
              ForeColor="#333333"
              GridLines="None" 
              AutoGenerateDeleteButton="true">

              <AlternatingRowStyle BackColor="White" />
              <EditRowStyle BackColor="#2461BF" />
              <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
              <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
              <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
              <RowStyle BackColor="#EFF3FB" />
              <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
              <SortedAscendingCellStyle BackColor="#F5F7FB" />
              <SortedAscendingHeaderStyle BackColor="#6D95E1" />
              <SortedDescendingCellStyle BackColor="#E9EBEF" />
              <SortedDescendingHeaderStyle BackColor="#4870BE" />

          </asp:GridView>

        </form>



  

</body>
</html>

